build: off

image:
- Ubuntu

clone_folder: /home/appveyor/appveyor_prs

environment:
  GOPATH: /home/appveyor/gopath

branches:
  only:
    - master

stack: go 1.11

install:
- export GOPATH=/home/appveyor/gopath
- echo $PATH
- echo $GOPATH
- export PATH=$GOPATH%/bin:$PATH
- printenv
- git status
- sudo apt-get --yes install jq
- go version
- go env
- go get -v -t github.com/eswdd/appveyor_pr_checker
- cd /home/appveyor/gopath/src/github.com/eswdd/appveyor_pr_checker
- go build ./...
- ls

test_script:
  - cd /home/appveyor/appveyor_prs
  - bash -x ./appveyor.sh

