pull_requests:
  do_not_increment_build_number: true
version: build-{build}

environment:
  GOPATH: /home/appveyor/gopath
  GITHUB_TOKEN:
    secure: hELAI4G5fGKHffQInpsVRVdbEXvSQrbY6JpDj8irGLWKrB/fimFXV+wyZrC8ERkM

build: off

image:
- Ubuntu

clone_folder: /home/appveyor/appveyor_prs

branches:
  only:
    - master

stack: go 1.11

install:
- sudo apt-get --yes install jq
- export GOPATH=/home/appveyor/gopath
- echo $PATH
- echo $GOPATH
- export PATH=$GOPATH%/bin:$PATH
- git status
- go version
- go env
- go get -v -t github.com/eswdd/appveyor_pr_checker
- cd /home/appveyor/gopath/src/github.com/eswdd/appveyor_pr_checker
- go build ./...
- ls

test_script:
  - cd /home/appveyor/appveyor_prs
  - ./appveyor.sh

